### ISSUE TITLE
make ensure!() return Ok(())

### ISSUE THREAD

**Issue by aruediger** [dtolnay/anyhow#294]
`ensure!()` currently evaluates to `()` on success so one has to write
```rust
fn check() -> anyhow::Result<()> {
  ensure!(true);
  Ok(())
}
```
or
```rust
fn check() -> anyhow::Result<()> {
  Ok(ensure!(true))
}
```

If ensure would provide an `else` branch that returns `Ok(())` then this would work:
```rust
fn check() -> anyhow::Result<()> {
  ensure!(true)
}
```
This might break backwards compatibiity, though.

**Comment by dtolnay** [comment]
I think this is better with the current signature.

**Comment by sirewix** [comment]
The current design makes it impossible to add additional context to the error. I like that `ensure` without arguments can print lhs and rhs values
```rust
ensure!(a == b);
```
But as soon as I want to add additional context
```rust
ensure!(a == b, "ab mismatch in transaction {tx_id}");
```
It's stops doing that. It could be avoided if `ensure` returned `Result`:
```rust
ensure!(a == b).context(format!("ab mismatch in transaction {tx_id}"))?;
```
There's very little practicality in making it return `()` instead of `Result<()>`
