### ISSUE TITLE
Performance of capturing the backtrace?

### ISSUE THREAD

**Issue by dpc** [dtolnay/anyhow#41]
I remember with `failure` there was a discussion on optimizing the backtrace handling. How does this look in `anyhow`?

**Comment by dtolnay** [comment]
As far as I know, this library has every relevant performance optimization from `failure` and a couple more. Do you have a link to the backtrace handling discussion that you have in mind?

**Comment by dpc** [comment]
I think it is mostly about the things brought in https://github.com/rust-lang-nursery/failure/issues/246 which still seems open. I actually don't care that much myself, I was just curious.

**Comment by dtolnay** [comment]
That issue may be from before backtrace-rs did lazy symbolization of backtraces. Capturing is always cheap, resolving symbols for printing is potentially slow depending on platform. Poor separation between these was why people sometimes had performance trouble with backtraces in error-chain. In any case, the whole thing is gated behind RUST_LIB_BACKTRACE so even if it were slow it would be opt-in.

If someone has an actual performance problem then I can take a look, but I don't expect any noticeable performance impact from modern backtraces.

**Comment by loyd** [comment]
> Capturing is always cheap.

Indeed, it's not that simple and depends on the way of capturing.

By default, `backtrace` crate uses `libunwind` to capture stack traces. `libunwind` uses dwarf information during capturing in order to determine the start of a stack frame. So, there is no big difference between capturing and resolving here. On my laptop capturing 10 frames requires around enormous 6us with resolving and 4us without.

When compiling with `-fno-omit-frame-pointer` (`-C force-frame-pointers=yes` in rust) it's possible to use the base pointer (`rbp`) and capturing become much cheaper: around 100ns per 10 frames.
