### ISSUE TITLE
Second type parameter for `Context` is redundant

### ISSUE THREAD

**Issue by omni-viral** [dtolnay/anyhow#68]
For one, second parameter is not used anywhere in the trait.
For two, it creates weird effects, like `Option<T>` implementing `Context<T, Infallible>` while `Result<T, Infallible>` is homomorphic to `T` and `Option<T>` is homomorphic to `Result<T, ()>`.

**Comment by dtolnay** [comment]
This is intentional to reserve the possibility of adding a combinator which accepts the error value as an argument, i.e. FnOnce(&amp;E) -&gt; C, like what exists in failure's ResultExt. The use of Infallible instead of () is also intentional because that combinator should not be callable at all in the Option case.

**Comment by omni-viral** [comment]
You still can have code path with `Infallible` value. It is never reachable though.
To completely disallow calling it for `Option` I'd make it a separate trait implemented only for `Result`.
