### ISSUE TITLE
Add Clone support

### ISSUE THREAD

**Issue by krojew** [dtolnay/anyhow#7]
Currently anyhow::Error is not Clone, which makes the crate hard (or even impossible) to use with some mock crates in tests, e.g. mock-it.

**Comment by dtolnay** [comment]
In order to provide a Clone impl we would need to do either of:

- require that you can only construct anyhow::Error from errors that are Clone, which would make it incompatible with many error types in the wild like io::Error and serde_json::Error; or
- reference-count the internal error.

The first one seems bad to me and the second one makes it impossible to downcast by value which also seems bad (fwiw failure came to the same conclusion in https://github.com/rust-lang-nursery/failure/issues/148).

Is there a way for you to work around this by using Rc\<Error\> or Arc\<Error\> in the tests?

**Comment by krojew** [comment]
My first though was about using Arc, but that introduced a ton of changes which were not really needed from the api standpoint. Unfortunately, the work required outweighed the benefit of using anyhow. And there's also the possibility of passing error across 3rd party crates which don't wrap results in anything.

**Comment by dtolnay** [comment]
That's too bad. I am sorry to hear that it didn't work out for your use case!
