### ISSUE TITLE
Interop with tide::Error (http_types::Error)

### ISSUE THREAD

**Issue by dnsco** [dtolnay/anyhow#89]
First off, thanks for the great library!

I'm using tide which will convert ```StdErrror``` to a tide::Error, but all of the constructors for tide::Error, will wrap the error in anyhow, using ```anyhow::Error::new(e)``` this fails because
```
 .map_err(|e| anyhow::Error::new(e))
   |                                             ^ the trait `std::error::Error` is not implemented for `anyhow::Error`
... 
         E: StdError + Send + Sync + 'static,
            -------- required by this bound in `anyhow::error::<impl anyhow::Error>::new`
```

I tried creating a helper method to leverage the conversion that you've been advising in similar via an explicit into() call at method invocation ```to_tide_error(e.into())```:

```
    pub fn to_tide_error(e: Box<dyn std::error::Error + Send + Sync + 'static>) -> tide::Error {
        tide::Error::from(e)
    }
```

this is yielding Error
```
error[E0277]: the size for values of type `dyn std::error::Error + std::marker::Send + std::marker::Sync` cannot be known at compilation time
  --> src/api.rs:60:27
   |
60 |         tide::Error::from(e)
   |                           ^ doesn't have a size known at compile-time
   |
   = help: the trait `std::marker::Sized` is not implemented for `dyn std::error::Error + std::marker::Send + std::marker::Sync`
   = note: to learn more, visit <https://doc.rust-lang.org/book/ch19-04-advanced-types.html#dynamically-sized-types-and-the-sized-trait>
   = note: required because of the requirements on the impl of `std::error::Error` for `std::boxed::Box<dyn std::error::Error + std::marker::Send + std::marker::Sync>`
   = note: required because of the requirements on the impl of `std::convert::From<std::boxed::Box<dyn std::error::Error + std::marker::Send + std::marker::Sync>>` for `http_types::error::Error`
   = note: required by `std::convert::From::from`
```

I eventually found: https://github.com/dtolnay/anyhow/issues/63#issuecomment-591011454 where you advise using thiserror.

It was quite a bit of digging to find that solution. I'm kinda bummed that I have to use another library to use a library that leverages anyhow.

I don't understand the coherence issues, but I've seen them referenced in other issues. I'm raising this issue mostly out of concern around the sizing issue that I don't completely understand making that ```From``` impls in anyhow less effective in practical usage.

Thanks again for anyhow. Sorry for what's basically a repeat question, but I hope that putting this together could help address this with some code or documentation changes that make these issues happen less and save everyone time in the long run.

**Comment by dtolnay** [comment]
It would be reasonable for tide::Error to have a constructor that takes Box\<dyn Error + Send + Sync + 'static\> so that you can call it with `tide::Error::some_constructor_name(your_error.into())`, relying on the implementation of Into\<Box\<dyn Error + Send + Sync + 'static\>\> for anyhow::Error.

<br>

> I'm raising this issue mostly out of concern around the sizing issue that I don't completely understand

That error is just saying Box\<dyn Error + Send + Sync + 'static\> does not implement Error. The std::error::Error impl for Box<T> in the standard library only applies if T is not a trait object.

**Comment by JeanMertz** [comment]
I believe have a similar question:

An external library I'm using returns `anyhow::Error`. Underneath it's a `io::Error`. I want to use `thiserror` to wrap this error in my own type.

Something like this works:

```rust
#[derive(Debug, Display, Error)]
pub enum MyError {
    /// missing source
    MissingSource(#[from] anyhow::Error),
}
```

But I'm trying to figure out how I can make it `#[from] std::io::Error` since `anyhow::Error` could be any type of error.

One solution I could see is downcasting the generic error and add a second `MyError::Uknown` type to fall back to, but is that the conventional solution here, since that seems to be a relatively verbose solution that requires me to map the errors vs just appending the `?` operator.

I'd rather have it automatically fall back to the unknown error using the technique described in `thiserror`:

```rust
#[derive(Debug, Display, Error)]
pub enum MyError {
    /// missing source
    MissingSource(#[from] std::io::Error),
    // ^ use this if `anyhow::Error` downcasts to `io::Error`

    #[error(transparent)]
    Other(#[from] anyhow::Error)
    // ^ use this if no other error matches
}
```


Apologies if my question is completely different, I'm happy to open a new issue if that helps.

**Comment by dnsco** [comment]
@dtolnay thanks for your fast advice. with your help, I was able to find a constructor with a suitable signature ```tide::Error::from_str``` which passes anything that meets those trait bounds to ``anyow::Error::msg```. It looses the backtrace, but  moves me forward.

**Comment by dnsco** [comment]
https://github.com/http-rs/http-types/issues/88

**Comment by dtolnay** [comment]
I think that issue is different. That is about converting http_types::Error into a different error type, not converting a different error type into http_types::Error.

**Comment by bbigras** [comment]
Can we use https://docs.rs/tide/0.9.0/tide/struct.Error.html#method.new directly with anyhow::Error?
